export const REDUCER_NAME = "cities";
export const CITIES_LOADING = `${REDUCER_NAME}/CITIES_LOADING`;
export const SET_CITIES = `${REDUCER_NAME}/SET_CITIES`;
export const SET_COUNTRIES = `${REDUCER_NAME}/SET_COUNTRIES`;
export const RESET_CITIES = `${REDUCER_NAME}/RESET_CITIES`;
export const RESET_COUNTRIES = `${REDUCER_NAME}/RESET_COUNTRIES`;
