export const REDUCER_NAME = "editProfile";
export const SET_LOADING = `${REDUCER_NAME}/SET_LOADING`;
export const SET_EDIT_PROFILE = `${REDUCER_NAME}/SET_EDIT_PROFILE`;
export const SET_VALIDATION_MESSAGES = `${REDUCER_NAME}/SET_VALIDATION_MESSAGES`;
export const RESET_VALIDATION_MESSAGES = `${REDUCER_NAME}/RESET_VALIDATION_MESSAGES`;
