export const REDUCER_NAME = "home";
export const SET_LOADING = `${REDUCER_NAME}/SET_LOADING`;
export const SET_HOME_CONTENT = `${REDUCER_NAME}/SET_HOME_CONTENT`;
export const SET_WISHLIST_ITEMS = `${REDUCER_NAME}/SET_WISHLIST_ITEMS`;
export const LOAD_WISHLIST_ITEMS = `${REDUCER_NAME}/LOAD_WISHLIST_ITEMS`;
export const SET_WISHLIST_ITEM = `${REDUCER_NAME}/SET_WISHLIST_ITEM`;
export const RESET_WISHLIST_ITEM = `${REDUCER_NAME}/RESET_WISHLIST_ITEM`;
export const RESET_WISHLIST_ITEMS = `${REDUCER_NAME}/RESET_WISHLIST_ITEMS`;

export const DATA_TTL = 60000;
