export const REDUCER_NAME = "product";
export const SET_PRODUCT = `${REDUCER_NAME}/SET_PRODUCT`;
export const RESET_PRODUCT = `${REDUCER_NAME}/RESET_PRODUCT`;
export const SET_LOADING = `${REDUCER_NAME}/SET_LOADING`;
export const SET_PRODUCT_TITLE = `${REDUCER_NAME}/SET_PRODUCTS_TITLE`;
export const RESET_PRODUCT_TITLE = `${REDUCER_NAME}/RESET_PRODUCTS_TITLE`;
export const SET_WISHLIST_ITEMS = `${REDUCER_NAME}/SET_WISHLIST_ITEMS`;
export const LOAD_WISHLIST_ITEMS = `${REDUCER_NAME}/LOAD_WISHLIST_ITEMS`;
export const SET_WISHLIST_ITEM = `${REDUCER_NAME}/SET_WISHLIST_ITEM`;
export const RESET_WISHLIST_ITEM = `${REDUCER_NAME}/RESET_WISHLIST_ITEM`;
export const RESET_WISHLIST_ITEMS = `${REDUCER_NAME}/RESET_WISHLIST_ITEMS`;

export const DATA_TTL = 60000;
