export const REDUCER_NAME = "promotion";

export const SET_PROMOTION = `${REDUCER_NAME}/SET_PROMOTION`;
export const RESET_PROMOTION = `${REDUCER_NAME}/RESET_PROMOTION`;
export const SET_LOADING = `${REDUCER_NAME}/SET_LOADING`;
export const SET_PROMOTION_TITLE = `${REDUCER_NAME}/SET_PROMOTION_TITLE`;
export const RESET_PROMOTION_TITLE = `${REDUCER_NAME}/RESET_PROMOTION_TITLE`;
export const SET_WISHLIST_ITEMS = `${REDUCER_NAME}/SET_WISHLIST_ITEMS`;
export const LOAD_WISHLIST_ITEMS = `${REDUCER_NAME}/LOAD_WISHLIST_ITEMS`;
export const SET_WISHLIST_ITEM = `${REDUCER_NAME}/SET_WISHLIST_ITEM`;
export const RESET_WISHLIST_ITEM = `${REDUCER_NAME}/RESET_WISHLIST_ITEM`;
export const RESET_WISHLIST_ITEMS = `${REDUCER_NAME}/RESET_WISHLIST_ITEMS`;

export const DATA_TTL = 60000;
