export const REDUCER_NAME = "wishlist";

export const SET_LOADING = `${REDUCER_NAME}/SET_LOADING`;
export const IS_ERROR = `${REDUCER_NAME}/IS_ERROR`;
export const IS_WISHLIST_LOADED = `${REDUCER_NAME}/IS_WISHLIST_LOADED`;
export const SET_WISHLIST_PRODUCTS = `${REDUCER_NAME}/SET_WISHLIST_PRODUCTS`;
export const REMOVE_WISHLIST = `${REDUCER_NAME}/REMOVE_WISHLIST`;

export const DATA_TTL = 60000;
