export const REDUCER_NAME = "catalogueSort";
export const SET_LOADING = `${REDUCER_NAME}/SET_LOADING`;
export const SET_CATALOGUE_SORT = `${REDUCER_NAME}/SET_CATALOGUE_SORT`;
export const SET_CURRENCY_CODE = `${REDUCER_NAME}/SET_CURRENCY_CODE`;
export const SET_CURRENCY_INDEX = `${REDUCER_NAME}/SET_CURRENCY_INDEX`;
