version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/mikyajy-web/
hooks:
  BeforeInstall:
  - location: scripts/stop_app.sh
    timeout: 200
    runas: root
  AfterInstall:
  - location: scripts/build_dep.sh
    timeout: 200
    runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 30
      runas: root