export const REDUCER_NAME = "login";
export const SET_VALIDATION_MESSAGES = `${REDUCER_NAME}/SET_VALIDATION_MESSAGES`;
export const RESET_VALIDATION_MESSAGES = `${REDUCER_NAME}/RESET_VALIDATION_MESSAGES`;
